name: Run accessibility scans

on:
  workflow_dispatch: # enable run button on github.com
  schedule:
    - cron: "5 5 * * *" # Run daily at 5:05am

jobs:
  scan:
    name: Accessibility scan
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm install
      - name: Run scans
        run: npm run ci-scan
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Commit report to repo
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git commit -m ":clipboard: accessibility report from ${{ env.NOW }}"
          git push
