name: Run accessibility scans

on:
  workflow_dispatch: # enable run button on github.com
  schedule:
    - cron: "5 5 * * *" # Run daily at 5:05am

jobs:
  scan:
    name: Accessibility scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm install
      - name: Run scans
        run: npm run ci-scan
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "<h1>Evaluatory<h1>"
          replace: "<h1>Status</h1><p><a href=\"https://github.com/jsnmrs/status\">Status on GitHub</a></p>"
          regex: false
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "Handmade with ♥"
          replace: "Powered by <a href=\"https://darekkay.com/evaluatory/\">Evaluatory</a>. Handmade with ♥"
          regex: false
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Commit report to repo
        run: |
          git pull
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git commit -m ":clipboard: accessibility report from ${{ env.NOW }}"
          git push
